// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmesSeriesAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260807041521_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("Catalogo", b =>
                {
                    b.Property<Guid>("ItemCatalogoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duracao")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("JaAssistiu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemCatalogoId");

                    b.ToTable("Catalogos", (string)null);

                    b.HasData(
                        new
                        {
                            ItemCatalogoId = new Guid("0178c6d3-0216-41b3-82ea-a801c4d47412"),
                            DataLancamento = new DateTime(2019, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duracao = "03h02m",
                            Genero = "Ação",
                            ImagemUrl = "https://media.fstatic.com/bbDnPrCkQfkez98V3PQjPAHSGPo=/220x330/smart/filters:format(webp)/media/movies/covers/2019/03/d1nmwmgvaaajv5mjpg-large_4c7c.jpg",
                            JaAssistiu = true,
                            Tipo = "Filme",
                            Titulo = "Vingadores: Ultimato"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
